export const dogBreeds = [
    "Afghan Hound",
    "Airedale Terrier",
    "Akita",
    "Alaskan Malamute",
    "American Staffordshire Terrier",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Belgian Malinois",
    "Belgian Tervuren",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Border Collie",
    "Border Terrier",
    "Boston Terrier",
    "Boxer",
    "Brittany",
    "Bulldog",
    "Bullmastiff",
    "Bull Terrier",
    "Cane Corso",
    "Cavalier King Charles Spaniel",
    "Chihuahua",
    "Chinese Shar-Pei",
    "Chow Chow",
    "Cockapoo",
    "Cocker Spaniel",
    "Dachshund",
    "Dalmatian",
    "Dandie Dinmont Terrier",
    "Doberman Pinscher",
    "English Cocker Spaniel",
    "English Setter",
    "English Springer Spaniel",
    "French Bulldog",
    "German Shepherd",
    "Golden Retriever",
    "Great Dane",
    "Havanese",
    "Irish Setter",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Labrador Retriever",
    "Leonberger",
    "Lhasa Apso",
    "Maltese",
    "Mastiff",
    "Newfoundland",
    "Norwegian Elkhound",
    "Old English Sheepdog",
    "Papillon",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Pointer",
    "Pomeranian",
    "Poodle",
    "Portuguese Water Dog",
    "Pug",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Rough Collie",
    "Saint Bernard",
    "Saluki",
    "Samoyed",
    "Schnauzer",
    "Scottish Terrier",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "Staffordshire Bull Terrier",
    "Vizsla",
    "Weimaraner",
    "West Highland White Terrier",
    "Whippet",
    "Yorkshire Terrier",
    "Mixed Breed/Shelter Dog",
    "Other (Allow the option to Type In)"
]; 

export 
const catBreeds = [
    "Abyssinian",
    "Aegean",
    "American Bobtail",
    "American Curl",
    "American Ringtail",
    "American Shorthair",
    "American Wirehair",
    "Anatolian",
    "Arabian Mau",
    "Australian Mist",
    "Balinese",
    "Bengal",
    "Birman",
    "Bombay",
    "Brazilian Shorthair",
    "British Longhair",
    "British Shorthair",
    "Burmese",
    "Burmilla",
    "California Spangled",
    "Chantilly-Tiffany",
    "Chartreux",
    "Chausie",
    "Cheetoh",
    "Colorpoint Shorthair",
    "Cornish Rex",
    "Cymric",
    "Cyprus",
    "Devon Rex",
    "Donskoy",
    "Dragon Li",
    "Egyptian Mau",
    "European Shorthair",
    "Exotic Shorthair",
    "Foldex Cat",
    "German Rex",
    "Havana Brown",
    "Himalayan",
    "Japanese Bobtail",
    "Javanese",
    "Khao Manee",
    "Korat",
    "Korean Bobtail",
    "Kurilian Bobtail",
    "LaPerm",
    "Lykoi",
    "Maine Coon",
    "Manx",
    "Mekong Bobtail",
    "Minskin",
    "Mixed or Shelter Cat",
    "Munchkin",
    "Nebelung",
    "Norwegian Forest Cat",
    "Ocicat",
    "Oriental Bicolor",
    "Oriental Longhair",
    "Oriental Shorthair",
    "Persian",
    "Peterbald",
    "Pixie-bob",
    "Ragamuffin",
    "Ragdoll",
    "Russian Blue",
    "Scottish Fold",
    "Selkirk Rex",
    "Serengeti",
    "Serrade Petit",
    "Siamese",
    "Siberian",
    "Singapura",
    "Snowshoe",
    "Sokoke",
    "Somali",
    "Sphynx",
    "Thai",
    "Tonkinese",
    "Toyger",
    "Turkish Angora",
    "Turkish Van",
    "Ukrainian Levkoy",
    "Van Kedisi",
    "York Chocolate",
    "Domestic Longhair",
    "Domestic Medium Hair",
    "Domestic Shorthair",
    "Calico",
    "Tortoiseshell",
    "Tuxedo",
    "Tabby",
    "Bicolor",
    "Tricolor",
    "Ticked",
    "Smoke",
    "Tortie Point Siamese",
    "Seal Point Siamese",
    "Blue Point Siamese",
    "Chocolate Point Siamese",
    "Lynx Point Siamese",
    "Flame Point Siamese"
];

export const birdBreeds = [
"Abyssinian",
"Aegean",
"American Bobtail",
"American Curl",
"American Ringtail",
"American Shorthair",
"American Wirehair",
"Anatolian",
"Arabian Mau",
"Australian Mist",
"Balinese",
"Bengal",
"Birman",
"Bombay",
"Brazilian Shorthair",
"British Longhair",
"British Shorthair",
"Burmese",
"Burmilla",
"California Spangled",
"Chantilly-Tiffany",
"Chartreux",
"Chausie",
"Cheetoh",
"Colorpoint Shorthair",
"Cornish Rex",
"Cymric",
"Cyprus",
"Devon Rex",
"Donskoy",
"Dragon Li",
"Egyptian Mau",
"European Shorthair",
"Exotic Shorthair",
"Foldex Cat",
"German Rex",
"Havana Brown",
"Himalayan",
"Japanese Bobtail",
"Javanese",
"Khao Manee",
"Korat",
"Korean Bobtail",
"Kurilian Bobtail",
"LaPerm",
"Lykoi",
"Maine Coon",
"Manx",
"Mekong Bobtail",
"Minskin",
"Mixed or Shelter Cat",
"Munchkin",
"Nebelung",
"Norwegian Forest Cat",
"Ocicat",
"Oriental Bicolor",
"Oriental Longhair",
"Oriental Shorthair",
"Persian",
"Peterbald",
"Pixie-bob",
"Ragamuffin",
"Ragdoll",
"Russian Blue",
"Scottish Fold",
"Selkirk Rex",
"Serengeti",
"Serrade Petit",
"Siamese",
"Siberian",
"Singapura",
"Snowshoe",
"Sokoke",
"Somali",
"Sphynx",
"Thai",
"Tonkinese",
"Toyger",
"Turkish Angora",
"Turkish Van",
"Ukrainian Levkoy",
"Van Kedisi",
"York Chocolate",
"Domestic Longhair",
"Domestic Medium Hair",
"Domestic Shorthair",
"Calico",
"Tortoiseshell",
"Tuxedo",
"Tabby",
"Bicolor",
"Tricolor",
"Ticked",
"Smoke",
"Tortie Point Siamese",
"Seal Point Siamese",
"Blue Point Siamese",
"Chocolate Point Siamese",
"Lynx Point Siamese",
"Flame Point Siamese",
"Other (Not Listed)"
];
export  const fishSpecies = [
    "African Cichlids",
    "Anemonefish",
    "Angelfish (Freshwater)",
    "Anthias",
    "Arowana (e.g., Silver Arowana, Asian Arowana)",
    "Bala Shark",
    "Banggai Cardinalfish",
    "Betta (Siamese Fighting Fish)",
    "Blennies (e.g., Lawnmower Blenny)",
    "Butterflyfish",
    "Cardinal Tetra",
    "Cherry Barb",
    "Chromis (e.g., Green Chromis)",
    "Clown Loach",
    "Clown Triggerfish",
    "Clownfish",
    "Convict Cichlid",
    "Cory Catfish (e.g., Panda Cory, Bronze Cory)",
    "Damselfish",
    "Discus",
    "Dottyback",
    "Firefish",
    "Flame Angel",
    "Flowerhorn Cichlid",
    "Goby (e.g., Watchman Goby)",
    "Goldfish (e.g., Comet, Fantail, Oranda, Ryukin, Bubble Eye)",
    "Gourami (e.g., Dwarf Gourami, Blue Gourami, Pearl Gourami)",
    "Guppy",
    "Jawfish",
    "Killifish",
    "Koi",
    "Lionfish",
    "Mandarinfish",
    "Mollies",
    "Neon Tetra",
    "Oscars",
    "Pipefish",
    "Platies",
    "Plecostomus (Common Pleco)",
    "Pufferfish (e.g., Dwarf Puffer, Green Spotted Puffer)",
    "Ram Cichlids (e.g., German Blue Ram, Bolivian Ram)",
    "Rasboras (e.g., Harlequin Rasbora)",
    "Royal Gramma",
    "Rummy-nose Tetra",
    "Seahorses",
    "Swordtails",
    "Tiger Barb",
    "Wrasses (e.g., Six-Line Wrasse, Cleaner Wrasse)",
    "Yellow Tang",
    "Zebra Danio",
    "Other (Not Listed)"
];
export  const reptileSpecies = [
    "Ackie Monitor (Spiny-tailed Monitor)",
    "African Fat-tailed Gecko",
    "African Rock Python",
    "Amazon Tree Boa",
    "Anole species (e.g., Cuban Anole, Knight Anole)",
    "Ball Python (Royal Python)",
    "Bearded Dragon (e.g., Central Bearded Dragon)",
    "Blue-tongued Skink",
    "Box Turtles (e.g., Eastern Box Turtle, Three-toed Box Turtle)",
    "Burmese Python",
    "Caiman Lizards",
    "California Kingsnake",
    "Carpet Python",
    "Common Snapping Turtle",
    "Corn Snake",
    "Crested Gecko",
    "Day Geckos (e.g., Madagascar Day Gecko)",
    "Diamondback Terrapin",
    "Frilled Dragon",
    "Gargoyle Gecko",
    "Gopher Snake",
    "Greek Tortoise",
    "Green Anole (American Anole)",
    "Green Tree Python",
    "Hermann's Tortoise",
    "Hognose Snake (e.g., Western Hognose Snake)",
    "Iguana (e.g., Green Iguana, Lesser Antillean Iguana)",
    "Jackson's Chameleon",
    "Leopard Gecko",
    "Mata Mata Turtle",
    "Milk Snake",
    "Nile Monitor",
    "Painted Turtle",
    "Panther Chameleon",
    "Radiated Tortoise",
    "Rainbow Boa",
    "Red-eared Slider Turtle",
    "Red-footed Tortoise",
    "Red-tailed Boa (Boa Constrictor)",
    "Rhinoceros Iguana",
    "Rough Green Snake",
    "Russian Tortoise",
    "Savannah Monitor",
    "Soft-shelled Turtles (e.g., Florida Softshell Turtle)",
    "Spiny-tailed Lizard (Uromastyx)",
    "Sulcata Tortoise (African Spurred Tortoise)",
    "Tegus (e.g., Argentine Black and White Tegu)",
    "Tokay Gecko",
    "Veiled Chameleon (Yemen Chameleon)",
    "Water Dragons (e.g., Chinese Water Dragon, Australian Water Dragon)",
    "Other (Not Listed)"
];
export  const rodentSpecies = [
    "African Grass Rat",
    "Agouti",
    "Alpine Marmot",
    "Bamboo Rat",
    "Bank Vole",
    "Campbell's Dwarf Hamster",
    "Cane Rat",
    "Chinchilla",
    "Chinese Hamster",
    "Degu",
    "Dormouse (e.g., Edible Dormouse, Hazel Dormouse)",
    "Dwarf Hamster (e.g., Russian Dwarf Hamster)",
    "Eurasian Beaver",
    "European Ground Squirrel",
    "Fancy Mouse",
    "Fancy Rat (e.g., Dumbo Rat, Hairless Rat)",
    "Field Vole",
    "Gambian Pouched Rat",
    "Gerbil (e.g., Mongolian Gerbil)",
    "Giant Pouched Rat",
    "Guinea Pig (e.g., American Shorthair, Abyssinian, Peruvian, Silkie, Teddy)",
    "Himalayan Marmot",
    "Hutia (e.g., Cuban Hutia)",
    "Indian Palm Squirrel",
    "Laotian Rock Rat",
    "Lesser Egyptian Jerboa",
    "Long-tailed Chinchilla",
    "Moonrat (Though it's more closely related to hedgehogs)",
    "Natal Multimammate Mouse",
    "Northern Flying Squirrel",
    "Nutria (Coypu)",
    "Paca",
    "Patagonian Mara (Cavy)",
    "Prairie Dog",
    "Prevost's Squirrel",
    "Richardson's Ground Squirrel",
    "Roborovski Dwarf Hamster",
    "Short-tailed Chinchilla",
    "South African Ground Squirrel",
    "Southern Flying Squirrel",
    "Spiny Mouse",
    "Steppe Lemming",
    "Sugar Glider (Technically a marsupial, but often grouped with rodents in pet context)",
    "Syrian Hamster (Golden Hamster)",
    "Tarbagan Marmot",
    "Tuco-tuco",
    "Viscacha (e.g., Mountain Viscacha)",
    "Winter White Dwarf Hamster",
    "Wood Lemming",
    "Yellow-spotted Brush-furred Rat",
    "Other (Not Listed)"
];      
export  const horseBreeds = [
    "American Cream Draft",
    "American Paint Horse",
    "American Quarter Horse",
    "American Saddlebred",
    "Andalusian (Pura Raza Española)",
    "Appaloosa",
    "Arabian",
    "Ardennes",
    "Belgian Draft (Belgian Heavy Horse)",
    "Black Forest Horse",
    "Budyonny",
    "Camargue",
    "Cleveland Bay",
    "Clydesdale",
    "Connemara Pony",
    "Dales Pony",
    "Dartmoor Pony",
    "Dutch Warmblood",
    "Exmoor Pony",
    "Falabella (miniature horse)",
    "Fjord (Norwegian Fjord Horse)",
    "Freiberger",
    "Friesian",
    "Gypsy Vanner (Gypsy Horse)",
    "Hackney",
    "Haflinger",
    "Hanoverian",
    "Highland Pony",
    "Holsteiner",
    "Icelandic Horse",
    "Irish Cob (Tinker Horse)",
    "Irish Draught",
    "Irish Sport Horse",
    "Kentucky Mountain Saddle Horse",
    "Lipizzan (Lipizzaner)",
    "Lusitano",
    "Marwari",
    "Miniature Horse",
    "Missouri Fox Trotter",
    "Morgan",
    "Mustang",
    "Oldenburg",
    "Paso Fino",
    "Percheron",
    "Shetland Pony",
    "Shire",
    "Tennessee Walking Horse",
    "Thoroughbred",
    "Trakehner",
    "Welsh Pony (and Cob)",
    "Other (Not Listed)"
];
export const amphibianSpecies = [
    "African Clawed Frog (Xenopus laevis)",
    "Amazon Milk Frog",
    "American Toad (Anaxyrus americanus)",
    "Axolotl (Mexican Walking Fish)",
    "Barking Tree Frog",
    "Budgett's Frog",
    "Cane Toad (also known as Marine Toad or Giant Toad)",
    "Chinese Fire-bellied Newt",
    "Chubby Frog (Banded Bullfrog or Asian Painted Frog)",
    "Colorado River Toad (also known as the Sonoran Desert Toad)",
    "Couch's Spadefoot Toad",
    "Cuban Tree Frog",
    "Dart Frogs (e.g., Blue Dart Frog, Strawberry Poison Dart Frog)",
    "Eastern Newt (including the Red-spotted Newt subspecies)",
    "Eastern Tiger Salamander",
    "European Fire-bellied Toad",
    "Fire Salamander",
    "Giant African Bullfrog (Pixie Frog)",
    "Golden Tree Frog",
    "Gray Tree Frog",
    "Green and Black Poison Dart Frog",
    "Green Tree Frog",
    "Horned Frogs (e.g., Argentine Horned Frog, Cranwell's Horned Frog)",
    "Japanese Fire-bellied Newt",
    "Leopard Frog",
    "Long-toed Salamander",
    "Mantella Frogs (e.g., Golden Mantella)",
    "Marbled Salamander",
    "Narrow-mouthed Toads (e.g., Eastern Narrow-mouthed Toad)",
    "Oriental Fire-bellied Toad",
    "Pacific Tree Frog (or Chorus Frog)",
    "Red-eyed Tree Frog",
    "Red-legged Walking Frog",
    "Slimy Salamander",
    "Smooth Newt",
    "Southern Leopard Frog",
    "Spotted Salamander",
    "Spring Peeper",
    "Squirrel Tree Frog",
    "Surinam Toad (Pipa pipa)",
    "Tiger-leg Monkey Frog",
    "Tomato Frog",
    "Vietnamese Mossy Frog",
    "Western Tiger Salamander",
    "Whites Tree Frog (Dumpy Tree Frog)",
    "Wood Frog",
    "Yellow-bellied Toad",
    "Yellow-spotted Climbing Toad",
    "Yosemite Toad",
    "Waxy Monkey Tree Frog",
    "Other (Not Listed)"
]; 
export  const chickenBreeds = [
    "Ameraucana",
    "Ancona",
    "Andalusian",
    "Australorp",
    "Barnevelder",
    "Belgian d'Uccle",
    "Brahma",
    "Broilers (various breeds for meat production)",
    "Buckeye",
    "Campine",
    "Chantecler",
    "Cochin",
    "Cornish (or Indian Game)",
    "Crevecoeur",
    "Delaware",
    "Dominique",
    "Dorking",
    "Easter Egger (not a pure breed but known for blue/green eggs)",
    "Faverolles",
    "Frizzle (more of a feather type than a breed itself)",
    "Hamburg",
    "Houdan",
    "ISA Brown (a high-production laying hybrid)",
    "Java",
    "Jersey Giant",
    "Junglefowl (the wild ancestors of domestic chickens)",
    "La Fleche",
    "Lakenvelder",
    "Legbar (e.g., Cream Legbar)",
    "Leghorn",
    "Marans (e.g., Black Copper Marans known for dark brown eggs)",
    "Minorca",
    "Naked Neck (or Turken)",
    "New Hampshire Red",
    "Orpington (e.g., Buff Orpington)",
    "Plymouth Rock (e.g., Barred Rock)",
    "Polish (known for its prominent crest of feathers)",
    "Red Star (or Red Sex-Link)",
    "Rhode Island Red",
    "Sebright",
    "Silkie (known for its fluffy plumage and friendly nature)",
    "Sussex (e.g., Speckled Sussex)",
    "Welsummer",
    "White Star (or White Leghorn hybrid)",
    "Wyandotte (e.g., Silver Laced Wyandotte)",
    "Yokohama",
    "Other (Not Listed)"
  ];
export const duckBreeds = [
    "Abacot Ranger (also known as Hooded Ranger)",
    "Aylesbury",
    "Bali",
    "Black East Indian",
    "Blue Swedish",
    "Buff (or Buff Orpington)",
    "Call Duck",
    "Campbell (e.g., Khaki Campbell, known for its egg-laying ability)",
    "Cayuga",
    "Crested Duck",
    "Duclair",
    "Dutch Hookbill",
    "East Indies",
    "Harlequin",
    "Indian Runner (upright posture and known for egg-laying)",
    "Magpie",
    "Mallard (the wild type but sometimes kept as pets)",
    "Moscovy (a unique breed not closely related to other domestic ducks)",
    "Pekin (one of the most popular meat ducks and also a great pet)",
    "Rouen (resembles a Mallard but much larger)",
    "Saxony",
    "Silver Appleyard",
    "Silver Bantam",
    "Welsh Harlequin",
    "White-faced Black Spanish",
    "Other (Not Listed)"
];  
export const goatBreeds = [
    "Alpine",
    "American LaMancha (often just called LaMancha)",
    "Anglo-Nubian (or simply Nubian in the USA)",
    "Arapawa",
    "Australian Cashmere Goat",
    "Barbari",
    "Boer (primarily meat goats)",
    "British Alpine",
    "Cashmere (known for their soft undercoat used in cashmere wool)",
    "Damascus",
    "Dutch Landrace",
    "Fainting Goat (or Myotonic Goat, known for their 'fainting' episodes)",
    "French Alpine",
    "Golden Guernsey",
    "Jamnapari (or Jamunapari)",
    "Kiko",
    "Kinder (a cross between Pygmy and Nubian)",
    "Majorera",
    "Miniature Silky Fainting Goat (noted for their long silky coat)",
    "Nigerian Dwarf (small stature but good milk producers)",
    "Oberhasli (or simply Oberhasli in the USA)",
    "Osmanabadi",
    "Peacock Goat",
    "Pygmy (very popular as pets due to their small size)",
    "Pygora (a cross between Pygmy and Angora, raised for their fiber)",
    "Rangeland",
    "Rove",
    "Russian White",
    "Saanen",
    "San Clemente Island",
    "Savanna",
    "Sirohi",
    "Spanish Goat",
    "Stiefelgeiss (or Booted Goat)",
    "Toggenburg",
    "Valais Blackneck",
    "Verata",
    "West African Dwarf",
    "White Shorthaired Goat",
    "Zhongwei Goat",
    "Other (Not Listed)"
];
export const sheepBreeds = [
    "Awassi",
    "Babydoll Southdown (often kept as pets due to their small size)",
    "Balwen Welsh Mountain",
    "Beulah Speckled Face",
    "Bighorn Sheep (more of a wild species but included for completeness)",
    "Black Welsh Mountain",
    "Bluefaced Leicester",
    "Border Leicester",
    "California Red",
    "Castlemilk Moorit",
    "Charollais",
    "Cheviot",
    "Clun Forest",
    "Columbia",
    "Cormo",
    "Cotswold",
    "Dorper",
    "Dorset (both Horned and Polled varieties)",
    "East Friesian (known for high milk production)",
    "Finnsheep (or Finnish Landrace)",
    "Gotland",
    "Hampshire",
    "Hebridean",
    "Herdwick",
    "Icelandic (known for wool and unique meat flavor)",
    "Jacob (often recognized by their multiple horns)",
    "Karakul",
    "Kerry Hill",
    "Lincoln Longwool",
    "Manx Loaghtan",
    "Marino (noted for their high-quality wool)",
    "Navajo-Churro",
    "Norfolk Horn",
    "North Ronaldsay",
    "Oxford",
    "Polypay",
    "Racka",
    "Romanov",
    "Romney",
    "Rough Fell",
    "Rya",
    "Ryeland",
    "Scottish Blackface",
    "Shetland (small and hardy, known for wool)",
    "Soay",
    "Suffolk",
    "Swaledale",
    "Teeswater",
    "Texel",
    "Wiltshire Horn",
    "Other (Not Listed)"
  ];
export  const pigBreeds = [
    "American Landrace",
    "American Yorkshire",
    "Angeln Saddleback",
    "Berkshire",
    "British Landrace",
    "British Lop",
    "Chester White",
    "Duroc",
    "Gloucestershire Old Spot (often referred to as 'Old Spots')",
    "Gottingen Minipig (often used in research but can be pets)",
    "Hampshire",
    "Hereford",
    "Iberian",
    "Juliana Pig (also known as Miniature Painted Pig)",
    "KuneKune (a popular small-sized pig breed from New Zealand)",
    "Lacombe",
    "Large Black",
    "Large White",
    "Meishan",
    "Middle White",
    "Mulefoot",
    "Ossabaw Island",
    "Oxford Sandy and Black (also known as Oxford Forest Pig)",
    "Pietrain",
    "Potbelly or Vietnamese Potbellied (the most common 'pet' pig)",
    "Red Wattle",
    "Saddleback",
    "Swedish Landrace",
    "Tamworth",
    "Welsh",
    "Other (Not Listed)"
]; 

